# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: false
cache: packages

r_packages:
  - covr
  - lintr

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
