---
title: "test_vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
```

This is a sample vignette.

## マアジ

```{r}
year <- 2019
spcs <- "maaji"
maaji <- xl2df(fname = "../tests/testthat/excel/gyokaikyo_dummy_maaji.xlsx",
               year = year,
               spcs = spcs)
```

### 表
```{r}
df2table(maaji, year = 2016)
df2table(maaji, year = 2017)
df2table(maaji, year = 2018)
df2table(maaji, year = 2019)
```

```{r}
regional_graph(maaji,
               species_regex = "maaji",
               boundary_prefec = "\u548c\u6b4c\u5c71", # wakayama
               unit = "ton")

```

```{r}
# Dummy_prefec data is created becasue regional_graph requires
# at least one data in each region

dummy_chiba <- load_catch_dummy_kagoshima() %>% 
  dplyr::mutate(Prefec = "千葉")

data <- 
  dplyr::bind_rows(load_catch_dummy_kagoshima(),
                  dummy_chiba) %>% 
  dplyr::mutate(Catch_ton = as.numeric(Catch_ton))

regional_graph(data,
               species_regex = "マアジ",
               boundary_prefec = "鹿児島",
               unit = "ton")

```
### 加入量指標
```{r, echo = FALSE, fig.height = 4.5, fig.width = 7}
indexdata <- 
  parse_index("../tests/testthat/excel/index_maaji.xlsx", 2019) %>%
  dplyr::rename(Month = WHAT_IS_THIS) %>%
  dplyr::mutate(Place = str_remove(Place, "①|②|③|④|⑤|⑥"),
                Place = factor(Place),
                Year = as.integer(Year),
                LogIndex = as.double(LogIndex))
  
ybreaks <- c(0.001, 0.01, 0.1, 1, 10, 100, 1000)

ggplot(indexdata, aes(Year, LogIndex, group = Place, color = Place)) +
  geom_line(size = 1.2) +
  scale_y_log10(breaks=ybreaks,labels=ybreaks) +
  theme_bw(base_size = 14) +
  theme(legend.text=element_text(size=10))
```
